version: "3"
services:
  gconvertor:
    build:
      context: .
      args:
        HTTP_PROXY: {{PROXY}}
        HTTPS_PROXY: {{PROXY}}
    environment:
      LISTEN_ADDR: 0.0.0.0
      LISTEN_PORT: 8080
      EXPORT_PATH: /data
    ports: 
      - 8080:8080
    volumes:
      - /home/salarmgh/Workspace/videos:/data
